# Generated by Django 4.0.1 on 2022-08-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_message_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
